version: '3.7'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: django-oidc-test-dev
    image: django-oidc-test-dev:0.0.1
    tty: true
    stdin_open: true
    volumes:
      - ..:/django-oidc-test:delegated
      - ./.config/pip:/root/.config/pip
      - python:/python
    ports:
      - 8000:8000
      - 3000:3000
    depends_on:
      - database
  database:
    image: postgres

volumes:
  python:
